---
- name: Get Device Facts
  hosts: "{{ hosts }}"
  roles:
  - Juniper.junos
  connection: local
  gather_facts: yes

  vars_prompt:
  - name: hosts
    prompt: " \n \n Hi! I'm Your Shutdown Assistant Sarah, What Would You Like To Shutdown Today? \n \n please select your option below (case sensitive) \n  '101' '102' '103' '104' '105''201' '202' '203' '204' '205' 'OOB' 'SERVERS'"
    private: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ ansible_ssh_host }} port=830 timeout=5

  tasks:
    - name: INSTALL JUNOS CONFIG
      junos_install_config:
        host={{ ansible_ssh_host }}
        file=srx1.conf
        user=root
        passwd=eyeno1t2!
        logfile=deploysite.log
  
