---
- name: Get Device Facts
  hosts: "{{ hosts }}"
  roles:
  - Juniper.junos
  connection: local
  gather_facts: yes

  vars_prompt:
  - name: hosts
    prompt: " \n \n Hi! I'm Your Shutdown Assistant Sarah, What Would You Like To Shutdown Today? \n \n please select your option below (case sensitive) \n  '101' '102' '103' '104' '105''201' '202' '203' '204' '205' 'OOB' 'SERVERS'"
    private: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ ansible_ssh_host }} port=830 timeout=5

  tasks:
    - name: "TEST 1 - Ping Google DNS"
      junos_ping:
        host: "{{ ansible_ssh_host }}"
        user: "{{ ansible_ssh_user }}"
        passwd: "{{ ansible_ssh_pass }}"
        dest_ip: www.bbc.co.uk
      register: test1
      ignore_errors: True
#    - debug: var=test1

    - name: Check TEST 1
      assert:
        that:
          - test1.packet_loss == '0'
